version: '3.7'
services:
    mongodb:
        image: mongo:5.0.4-focal
        volumes:
            - /docker-data/mongodb:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
    main:
        image: rgabdullin/environment:latest
        build: 
            dockerfile: Dockerfile
            context: .
        ports:
            - 8888:8888
            - 8787:8787
            - 8786:8786
            - 6006:6006
        volumes:
            - /workspace:/workspace
        shm_size: 1g
        restart: unless-stopped
        runtime: nvidia
    rapidsai:
        image: rapidsai/rapidsai-core:21.10-cuda11.2-runtime-ubuntu20.04-py3.8
        ports:
            - 9888:8888
            - 9787:8787
            - 9786:8786
            - 9006:6006
        volumes:
            - /workspace:/rapids/notebooks/workspace
        restart: unless-stopped
        runtime: nvidia
        stdin_open: true
        tty: true
