version: '3.9'
services:
  jupyter-cpu:
    build:
      dockerfile: Dockerfile
      context: ubuntu-cpu
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
        mode: host
      - target: 8787
        published: 8787
        protocol: tcp
        mode: host
    volumes:
      - /workspace:/workspace
      - /dev:/dev
    secrets:
      - jupyter_password
    command: /run/scripts/entrypoint.sh
    networks: 
      - net1
secrets:
  jupyter_password:
    file: private/jupyter_password
networks:
  net1:
    external: false
    