version: '3.9'
services:
  main:
    image: rgabdullin/environment-ubuntu-cpu:latest
    build:
      dockerfile: .docker/Dockerfile
      context: ubuntu-cpu
    ports:
      - 8888:8888
    volumes:
      - ~/workspace/:/workspace/
      - /dev:/dev
    privileged: true
    secrets:
      - jupyter_password
    command: /run/scripts/entrypoint.sh
    networks: 
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
  mlflow:
      image: rgabdullin/mlflow-server:latest
      build:
        dockerfile: .docker/Dockerfile
        context: mlflow
      ports:
        - 5000:5000
      networks: 
        - internal
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: '4.0'
        placement:
          constraints:
            - "node.role==manager"
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 30s
secrets:
  jupyter_password:
    file: private/jupyter_password

networks:
  internal:
    external: false
