version: '3.9'
services:
    main:
        image: rgabdullin/environment-ubuntu-gpu:latest
        build: 
            dockerfile: Dockerfile
            context: ubuntu-gpu
        environment: 
            - NVIDIA_DRIVER_CAPABILITIES=all
            - NVIDIA_VISIBLE_DEVICES=all
        ports:
            - 8889:8888
            - 6006:6006
        volumes:
            - /workspace:/workspace
            - /dev:/dev
        privileged: true
        secrets:
            - jupyter_password
        networks:
            - net1
        command: /run/scripts/entrypoint.sh
        shm_size: 8g
        runtime: nvidia
        deploy:
            replicas: 1
            placement:
                constraints:
                    - "node.role==manager"
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 30s
secrets:
    jupyter_password:
        file: private/jupyter_password

networks:
    net1:
        external: false